### ISSUE TITLE
Howto: test release process (dry run)

### ISSUE THREAD

**Issue by fredrikhgrelland** [Skatteetaten/vagrant-hashistack#305]
We can test these changes while doing a new release? Or there are other ways?

_Originally posted by @zhenik in https://github.com/fredrikhgrelland/vagrant-hashistack/pull/303#issuecomment-688481698_

**Comment by Neha-Sinha2305** [comment]
This could be an option to dry-run workflow files locally : https://github.com/nektos/act
However, looks like it does not support macos-latest as a runner and most of the jobs in our workflow file run on macos-latest: https://github.com/nektos/act#runners

**Comment by fredrikhgrelland** [comment]
Every PR will now require a label denoting the change type `change/*` and will dry-run the release process on every CI-job.
A new label `action/release`will run the actual release process.
