### ISSUE TITLE
Demystify CD/CI workflow (release, pr, etc...)

### ISSUE THREAD

**Issue by Neha-Sinha2305** [Skatteetaten/vagrant-hashistack#332]
### Add:

- [ ] ~~workflow diagram (postponed)~~
- [x] docs for release process (PRIORITY -> update doc)
- [x] docs for submodule usage (Makefile:update-template)
- [ ] ~~how to migrate to GitLab (discussion)~~

**Comment by zhenik** [comment]
Maybe this year graph visualization will come [#88](https://github.com/github/roadmap/issues/88)

**Comment by zhenik** [comment]
According to #331 
- There is no need anymore to downstream changes from vagrant-hashistack `template/` directory to `vagrant-hashistack-template`. These are two different repositories.

**Comment by vitaly-semenov** [comment]
Hi, it would be great to have a more clear setup for testing, that can be used in GitLab CI/CD.
