### ISSUE TITLE
Project-bot

### ISSUE THREAD

**Issue by zhenik** [Skatteetaten/vagrant-hashistack#379]
> [project-bot](https://github.com/philschatz/project-bot) looks cool. We surely can give it a try. I will have a quick look.
> May be it needs the project board to be set to **public**.
> I wonder why our project board is set to **Private**, i guess we could turn it into public and restrict access for who can edit it.
> For example, this project board [vagrant-hashicorp](https://github.com/hashicorp/vagrant/projects/1) is public with restricted write access.

Nah, my project was public, so it wasn't that. Also FYI, Fredrik needs to be the one who installs the plugin. 

Yeah, I did see that issue, tried what the last guy commented, didn't work. No new issues with similar problems since that one either

_Originally posted by @pdmthorsrud in https://github.com/fredrikhgrelland/vagrant-hashistack/issues/338#issuecomment-698911070_

**Comment by fredrikhgrelland** [comment]
Wont do
