### ISSUE TITLE
Re-add pre_job

### ISSUE THREAD

**Issue by claesgill** [Skatteetaten/vagrant-hashistack#455]
## What is the issue?
In pr #454 we removed the `pre_job` workflow job that didn't work as expected. It skipped the `build` job that skipped the test and initially the release process as well. However, we still want this feature, but it needs to work as intended.

## Suggestion(s)/solution(s) [Optional]
This needs to be investigated further with the same marketplace-package or another.

## Checklist (after created issue)
- [x] Added label(s)
- [ ] Added to project
- [ ] Added to milestone

**Comment by fredrikhgrelland** [comment]
Wont do
