### ISSUE TITLE
Run each service on different VMs, as one would in prod.

### ISSUE THREAD

**Issue by stabenfeldt** [Skatteetaten/vagrant-hashistack#469]
## Feature description

Here we run consul, nomad and vault on the same VM.
Could we instead run each server on a separate VM? That would mimic how we architect things in a production system.

## Why is it needed?

It will be closer to the "real thing". Makes testing more useful here.

## Checklist (after created issue)
- [X] Added label(s)
- [ ] Added to project
- [ ] Added to milestone

**Comment by pdmthorsrud** [comment]
Are we sure it will actually mimic anything better than what we have now? What we want to test with this box is that modules themselves work on a functional level (does it use vault the correct way, does set upstreams correctly etc.). That would not be qualitatively different on an architecture where they are on separate nodes, would it?

**Comment by fredrikhgrelland** [comment]
@pdmthorsrud The premise of this enhancement would be to test consul/vault/nomad core services.
We will not do this using the current vagrant box.
